
    //Dec 31
    const SpellInfo = {
        "Aid": {
            name: "Aid",
            level: 2,
            range: 30,
            beneficial: true,
            spellType: "Misc",
            emote: "Each target’s hit point maximum and current hit points increase for the duration of the spell.",
            macro: "!Spell;Aid;%Level%;%Selected%;%Target1%;%Target2%;%Target3%",
            sound: "Angels",
            duration: 4800,
        },

        "Acid Splash": {
            name: "Acid Splash",
            level: 0,
            range: 60,
            spellType: "DirectAttack",
            autoHit: "No",
            base: '1d6',
            cLevel: {5: '2d6', 11: '3d6'},
            damageType: "acid",
            savingThrow: "dexterity",
            saveEffect: "No Damage",
            emote: '%%Caster%% hurls a bubble of acid at the target',
            sound: "Plasma",
            macro: '!Spell;Acid Splash;0;%Selected%;%Target%',
        },

        "Barkskin": {
            name: "Barkskin",
            level: 2,
            range: 5,
            beneficial: true,
            spellType: "Misc",
            emote: "You touch a willing creature. Until the spell ends, the target’s skin has a rough, bark-like appearance, and the target’s AC can’t be less than 16, regardless of what kind of armor it is wearing.",
            macro: "!Spell;Barkskin;2;%Selected%;%Target%",
            sound: "Entangle",
            concentration: true,
            duration: 600,
        },

        "Bless": {
            name: "Bless",
            level: 1,
            range: 30,
            beneficial: true,
            spellType: "Misc",
            emote: "You Bless up to 3 creatures of your choice within range.",
            macro: "!Spell;Bless;1;%Selected%;%Target1%;%Target2%;%Target3%",
            sound: "Angels",
            concentration: true,
            duration: 10,
        },

        "Blindness": {
            name: "Blindness",
            level: 2,
            range: 30,
            duration: 10,
            when: "endAll",
            spellType: "Misc",
            macro: "!Spell;Blindness;%Level%;%Selected%;%Target%",
            sound: "Sound",
            savingThrow: "constitution",
            saveText: " and is not Blinded",
            failText: " is Blinded",
            emote: "The Target can make a Constitution Save at the end of each of its turns.",
        },



        "Branding Smite": {
            name: "Branding Smite",
            level: 2,
            bonusAction: true,
            sLevel: [0,'2d6',"3d6","4d6","5d6","6d6","7d6"],
            range: 5,
            beneficial: true,
            duration: 10,
            concentration: true,
            spellType: "Misc",
            emote: "The next hit deals extra Radiant Damage and causes the target to be Illuminated, negating Invisibility",
            macro: "!Spell;Branding Smite;%Level%",
            sound: "Angels",
        },

        "Breathe": {
            name: "Breathe",
            level: 2,
            range: 15,
            spellType: "Area",
            duration: 10,
            base: '3d6',
            sLevel: [0,0,"3d6","4d6","5d6","6d6","7d6"],
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            area: 'Cone',
            areaEffect: "Damage",
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            sound: "Flames",
            fx: "breath-fire",
        },

        "Burning Hands": {
            name: "Burning Hands",
            level: 1,
            range: 15,
            spellType: "Area",
            base: '3d6',
            sLevel: [0,'3d6',"4d6","5d6","6d6","7d6","8d6"],
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            area: 'Cone',
            areaEffect: "Damage",
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            sound: "Flames",
            macro: '!Spell;Burning Hands;%Level%',
            fx: "breath-fire",
        },

        "Call Lightning": {
            name: "Call Lightning",
            level: 3,
            range: 120,
            spellType: "Area",
            area: "Square",
            areaEffect: "Damage",
            base: '3d10',
            sLevel: [0,0,'3d10','4d10','5d10','6d10','7d10'],
            damageType: "lightning",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            moveEffect: "objects",
            concentration: true,
            sound: "Thunder",
            macro: '!Spell;Call Lightning;%Level%',
            tempImg: "https://files.d20.io/images/470243589/MoDHQX6eZBXVXYY0Trj6lA/thumb.png?1767631375",
            tempSize: 10,
            emote: "",
            fx: 'explode-magic',
        },

         "Conjure Animals": {
            name: "Conjure Animals",
            beneficial: true,
            concentration: true,
            duration: 600,
            level: 3,
            range: 60,
            spellType: "Misc",
            emote: "You summon Fey spirits that take the form of beasts and appear in unoccupied spaces within 60ft. Options: 1 CR2 Beast or 2 CR1 Beasts or 4 CR 1/2 Beasts or 8 CR 1/4 beasts. They are friendly and obey verbal commands.",
            sound: "Angels",
            macro: "!Spell;Conjure Animals;%Level%;%Selected%",
        },

        "Crown of Madness": {
            name: "Crown of Madness",
            level: 2,
            range: 120,
            duration: 10,
            concentration: true,
            when: "endAll",
            spellType: "Misc",
            macro: "!Spell;Crown of Madness;2;%Selected%;%Target%",
            sound: "Sound",
            savingThrow: "wisdom",
            saveText: " and is not Charmed.",
            failText: " and is Charmed. While the target is charmed in this way, a twisted crown of jagged iron appears on its head, and a madness glows in its eyes. The charmed target must use its action before moving on each of its turns to make a melee attack against a creature other than itself that you mentally choose. On its subsequent turns, the caster must use its action to maintain control over the target, or the spell ends.",
            emote: "The Target can make a Wisdom Save at the end of each of its turns.",
        },




         "Cure Wounds": {
            name: "Cure Wounds",
            beneficial: true,
            level: 1,
            range: 5,
            heal: "1d8 + level + Bonus",
            spellType: "Misc",
            sound: "Angels",
            macro: "!Spell;Cure Wounds;%Level%;%Selected%",
        },

        "Dispel Magic": {
            name: "Dispel Magic",
            level: 3,
            bonusAction: false,
            duration: 1,
            beneficial: true,
            concentration: true,
            range: "Self",
            spellType: "Misc",
            macro: "!Spell;Dispel Magic;%Level%;%Selected%",
            emote: "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell’s level. On a successful check, the spell ends. At Higher Levels. When you cast this spell using a spell slot o f 4th level or higher, you automatically end the effects o f a spell on the target if the spell’s level is equal to or less than the level o f the spell slot you used.",             
            sound: "Angels",
        },       



        "Divine Favour": {
            name: "Divine Favour",
            level: 1,
            bonusAction: true,
            duration: 10,
            beneficial: true,
            concentration: true,
            range: "Self",
            spellType: "Misc",
            macro: "!Spell;Divine Favour;1;%Selected%",
            emote: "Your prayer empowers you with divine radiance. Until the spell ends, your weapon attacks deal an extra 1d4 radiant damage on a hit.<br>Casting this only takes a Bonus Action",
            sound: "Angels",
        },       

        "Dragon's Breath": {
            name: "Dragon's Breath",
            level: 2,
            bonusAction: true,
            range: 5,
            duration: 10,
            concentration: true,
            beneficial: true,
            spellType: "Misc",
            sound: "Ding",
            damageType: "fire",
            emote: "%%Target%% gains the ability to breath magical in a 15 foot cone.",
            macro: "!Spell;Dragon's Breath;%Level%;%Selected%;%Target%;?{Energy Type|Acid|Cold|Fire|Lightning|Poison}",
            alternates: ["damageType"],
        },

        "Eldritch Blast": {
            //need to modify the macro at level 5 to have 2 targets
            name: "Eldritch Blast",
            level: 0,
            range: 120,
            spellType: "DirectAttack",
            autoHit: "No",
            base: '1d10',
            damageType: "force",
            emote: '%%Caster%% fires a beam of eldritch energy at the target',
            sound: "Plasma",
            macro: '!Spell;Eldritch Blast;0;%Selected%;%Target%',
        },


        "Entangle": {
            name: "Entangle",
            level: 1,
            range: 90,
            duration: 10,
            concentration: true,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            savingThrow: "strength",
            when: "action",
            conditionImmune: "restrained",
            saveText: " and remains free to act",
            failText: " and is restrained by the vines",
            moveEffect: "map",
            sound: "Entangle",
            macro: '!Spell;Entangle;1',
            emote: "The Area remains Difficult Ground. Restrained Creatures must use their Action, making a Strength Save to Break out.",
            tempImg: 'https://files.d20.io/images/464592489/MlFXxUdwYnkx-S5mHam-KQ/thumb.png?1763430837',
            tempSize: 20,
            fx: "explode-slime",
        },

        "Explosive Blast": {
            //Izek
            name: "Explosive Blast",
            level: 0,
            range: 90,
            spellType: "Area",
            area: "Square",
            areaEffect: "Damage",
            base: '2d6',
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",       
            sound: "",
            macro: '!Spell;Explosive Blast;0',
            tempImg: "https://files.d20.io/images/469625735/mK7gnOSOteATSiJs5Z7riA/thumb.png?1767216572",
            tempSize: 10,
            emote: "A target that fails the save is also knocked prone.",
            fx: 'explode-fire',
        },



        "Faerie Fire": {
            name: "Faerie Fire",
            level: 1,
            range: 60,
            duration: 10,
            concentration: true,
            spellType: "Area",
            area: "Square",
            areaEffect: "Effect",
            savingThrow: "dexterity",
            failText: " and is outlined by Faerie Fire",
            sound: "FFire",
            macro: '!Spell;Faerie Fire;1',
            tempImg: "https://files.d20.io/images/464592488/Ol6oEZ2kLqqfV-fEBHrq5Q/thumb.png",
            tempSize: 20,
            fx: 'explode-magic',
        },

        "Fear": {
            name: "Fear",
            level: 3,
            range: 30,
            concentration: true,
            duration: 10,
            spellType: "Area",
            savingThrow: "wisdom",
            area: 'Cone',
            areaEffect: "Effect",
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            sound: "Beam",
            macro: '!Spell;Fear;%Level%',
            fx: "breath-magic",
            failText: " and is Feared",
            failTextAll: "Creatures that fail drop whatever they are holding and become frightened for the duration. While frightened by this spell, a creature must take the Dash action and move away from the caster by the safest available route on each of its turns, unless there is nowhere to move. If the creature ends its turn in a location where it doesn’t have line of sight to the caster, the creature can make a Wisdom saving throw. On a successful save, the spell ends for that creature.",
        },



        "Fire Bolt": {
            name: "Fire Bolt",
            level: 0,
            spellType: "DirectAttack",
            range: 120,
            autoHit: "No",
            base: '1d10',
            cLevel: {5: '2d10', 11: '3d10'},
            damageType: "fire",
            sound: "Laser",
            emote: "A mote of fire is hurled toward the target",
            fx: "",
            macro: '!Spell;Fire Bolt;0;%Selected%;%Target%',
        },

        "Flame Blade": {
            name: "Flame Blade",
            level: 2,
            bonusAction: true,
            duration: 100,
            concentration: true,
            spellType: "Misc",
            sound: "Woosh",
            macro: '!Spell;Flame Blade;%Level%',
            fx: 'burn-fire',
            emote: "%%Caster%% evokes a Fiery Blade as a Bonus Action",            
        },

        "Flame Volley": {
            //Izek
            name: "Flame Volley",
            level: 0,
            range: 60,
            spellType: "Area",
            area: "Square",
            areaEffect: "Damage",
            base: '2d6',
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "No Damage",       
            sound: "",
            macro: '!Spell;Flame Volley;0',
            tempImg: "https://files.d20.io/images/469625735/mK7gnOSOteATSiJs5Z7riA/thumb.png?1767216572",
            tempSize: 10,
            fx: 'explode-fire',
        },
        "Flaming Wave": {
            //Izek
            name: "Flaming Wave",
            level: 0,
            range: 60,
            spellType: "Area",
            area: "Line",
            areaEffect: "Damage",
            base: '2d10',
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "No Damage",       
            sound: "Laser",
            macro: '!Spell;Flaming Wave;0',
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            fx: 'beam-fire',
        },


        "Flaming Sphere": {
            level: 2,
            name: "Flaming Sphere",
            range: 60,
            spellType: "Ongoing",
            duration: 10,
            concentration: true,
            base: '2d6',
            sLevel: [0,0,"2d6","3d6","4d6","5d6","6d6"],
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            area: 'special',
            effect: "Damage",
            tempImg: 'https://files.d20.io/images/467704024/63vhnKhZNoVRWYEwBz8uTQ/thumb.png?1765676435',
            tempSize: 15,
            sound: "Inferno",
            fx: "glow-fire",
            macro: '!Spell;Flaming Sphere;%Level%',
            emote: "A sphere of fire appears within range. Any creature entering the sphere takes damage. The sphere can be moved 30 feet and into other creatures, who take damage, stopping the sphere",
            charID: '-OgPVj8fUQkF1eJDvbWI',
        },

        "Fog Cloud": {
            name: "Fog Cloud",
            level: 1,
            spellType: "Area",
            area: "Square",
            sound: "Woosh",
            range: 120,
            duration: 600,
            concentration: true,
            emote: 'The Dense Fog blocks vision into/out of or through it.<br>The Fog can be blown away by a strong wind.',
            areaEffect: "Graphic",
            moveEffect: "map",
            macro: '!Spell;Fog Cloud;%Level%',
            tempImg: "https://files.d20.io/images/464601122/Z_72GfzK6nldIvjjv9Kusw/thumb.png?1763436289",
            tempSize: 'Level * 40',
        },

        "Guiding Bolt": {
            name: "Guiding Bolt",
            level: 1,
            spellType: "DirectAttack",
            range: 120,
            autoHit: "No",
            base: '4d6',
            sLevel: [0,'4d6',"5d6","6d6","7d6","8d6","9d6"],
            damageType: "radiant",
            note: "",
            sound: "Laser",
            emote: "A flash of bright light streaks toward the target. If it hits, the next attack against this creature has Advantage",
            fx: "beam-magic",
            macro: '!Spell;Guiding Bolt;%Level%;%Selected%;%Target%',
        },

        "Gust of Wind": {
            name: "Gust of Wind",
            level: 2,
            concentration: true,
            range: 60,
            spellType: "Area",
            area: "Line2",
            areaEffect: "Effect",
            savingThrow: "strength",
            failText: " is pushed 15 feet away",
            sound: "Wind",
            macro: "!Spell;Gust of Wing;2",
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            emote: "The gust disperses gas or vapor, and it extinguishes candles, torches, and similar unprotected flames in the area. It causes protected flames, such as those of lanterns, to dance wildly and has a 50 percent chance to extinguish them.",
            tempSize: 5,
            fx: "beam-smoke",
        },



         "Healing Word": {
            name: "Healing Word",
            level: 1,
            bonusAction: true,
            beneficial: true,
            range: 60,
            heal: "1d4 + level + Bonus",
            spellType: "Misc",
            sound: "Angels",
            emote: "As a Bonus Action",
            macro: "!Spell;Healing Word;%Level%;%Selected%;%Target%",
        },

        "Heat Metal": {
            name: "Heat Metal",
            level: 2,
            range: 60,
            duration: 10,
            concentration: true,
            when: "start",
            macro: "!Spell;Heat Metal;%Level%;%Selected%;%Target%",
            sound: "Woosh",
            savingThrow: "constitution",
            emote: "",
            when: "start",
            spellType: "DirectAttack",
            saveText: " and may drop/remove the Object<br>",
            failText: " and must drop/remove the Object<br>",
            autoHit: "Yes",
            base: '2d8',
            sLevel: [0,0,"2d8","3d8","4d8","5d8","6d8"],
            damageType: "fire",
            saveEffect: "Special",
        },


        "Heroism": {
            name: "Heroism",
            beneficial: true,
            level: 1,
            range: 5,
            spellType: "Misc",
            emote: "%%Target%% is imbued with bravery, immune to being frightened and gains temporary hp each round.",
            macro: "!Spell;Heroism;1;%Selected%;%Target%",
            sound: "Angels",
            concentration: true,
            duration: 10,
        },


        "Hold Person": {
            name: "Hold Person",
            level: 2,
            range: 60,
            duration: 10,
            concentration: true,
            when: "endAll",
            spellType: "Misc",
            macro: "!Spell;Hold Person;%Level%;%Selected%;%Target%",
            sound: "Sound",
            savingThrow: "wisdom",
            saveText: " and is not Held.",
            failText: " and is Held",
            emote: "The Target can make a Wisdom Save at the end of each of its turns.",
        },

        "Lightning Bolt": {
            name: "Lightning Bolt",
            level: 3,
            range: 100,
            spellType: "Area",
            area: "Line",
            areaEffect: "Damage",
            base: '8d6',
            sLevel: [0,0,'8d6','9d6','10d6','11d6'],
            damageType: "lightning",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",       
            sound: "Thunder",
            macro: '!Spell;Lightning Bolt;3',
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            fx: 'beam-magic',
        },




        "Mage Armour": {
            name: "Mage Armour",
            level: 1,
            range: 5,
            spellType: "Misc",
            emote: "You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends.The target’s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.",
            macro: "!Spell;Mage Armour;1;%Selected%;%Target%",
            sound: "Angels",
        },

        "Magic Missile": {
            name: "Magic Missile",
            level: 1,
            range: 120,
            spellType: "DirectAttack",
            autoHit: "Yes",
            base: '3d4+3',
            sLevel: [0,'3d4+4','4d4+4','5d4+5','6d4+6','7d4+7'],
            damageType: "force",
            macro: '!Spell;Magic Missile;%Level%;%Selected%;%Target%',
            emote: "%%Caster%% creates glowing darts of magical force which strike the target",
            sound: "Splinter2",
            fx: "missile-magic",
        },

        "Magic Weapon": {
            name: "Magic Weapon",
            level: 2,
            bonusAction: true,
            beneficial: true,
            range: 5,
            spellType: "Misc",
            emote: "%%Caster%% enchants a weapon to be magical!",
            macro: "!Spell;Magic Weapon;%Level%;%Selected%;%Target%",
            sound: "FFire",
            concentration: true,
            duration: 600,

        },

        "Melf's Acid Arrow": {
//fix
            name: "Melf's Acid Arrow",
            level: 2,
            spellType: "DirectAttack",
            range: 90,
            autoHit: "No",
            base: '4d4',
            sLevel: [0,0,'4d4','5d4','6d4','7d4','8d4'],
            damageType: "acid",
            sound: "Laser",
            emote: "A shimmering green arrow streaks toward the target and burst in a spray of acid. On a miss, the target still takes 5 acid damage",
            fx: "rocket-slime",
            macro: '!Spell;Melfs Acid Arrow;%Level%;%Selected%;%Target%',
        },



        "Moonbeam": {
            level: 2,
            name: "Moonbeam",
            range: 120,
            spellType: "Ongoing",
            duration: 10,
            concentration: true,
            base: '2d10',
            sLevel: [0,0,"2d10","3d10","4d10","5d10","6d10"],
            damageType: "radiant",
            savingThrow: "constitution",
            saveEffect: "Half Damage",
            area: 'special',
            effect: "Damage",
            tempImg: 'https://files.d20.io/images/466342179/VLWwiNSk5g-QKmRkYZ77qA/thumb.png?1764706936',
            tempSize: 10,
            sound: "Beam",
            fx: "glow-holy",
            macro: '!Spell;Moonbeam;%Level%',
            emote: "A silvery beam of pale light shines down in a 5-foot- radius, 40-foot-high cylinder centered on a point within range. Creatures entering or starting their turn in the Moonbeam take damage. The Caster can move the Beam on each of their turns up to 60 feet.",
            charID: '-OfVsgHiqLOZjV357ox_',
        },

        "Produce Flame": {
            name: "Produce Flame",
            level: 0,
            range: 30,
            autoHit: "No",
            spellType: "DirectAttack",
            base: '1d8',
            cLevel: {5: '2d8', 11: '3d8'},
            damageType: "fire",
            sound: "Plasma",
            macro: '!Spell;Produce Flame;0;%Selected%;%Target%',
            emote: "%%Caster%% hurls a ball of flame at the target",
            fx: "",
        },

        "Protection from Energy": {
            level:3,
            name: "Protection from Energy",
            duration: 600,
            beneficial: true,
            concentration: true,
            range: 5,
            alternates: ["energyType"],
            spellType: "Misc",
            emote: "The creature you touch has resistance to one damage type of your choice",
            macro: "!Spell;Protection from Energy;3;%Selected%;%Target%;?{Energy Type|Acid|Cold|Fire|Lightning|Thunder}",
            sound: "Angels",
        },


        "Protection from Evil and Good": {
            level:1,
            name: "Protection from Evil and Good",
            duration: 100,
            beneficial: true,
            concentration: true,
            range: 5,
            spellType: "Misc",
            emote: "The creature you touch is granted Protection against certain creatures.",
            macro: "!Spell;Protection from Evil and Good;1;%Selected%;%Target%",
            sound: "Angels",
        },

        "Putrid Radiance": {
            name: "Putrid Radiance",
            level: 2,
            range: 30,
            spellType: "Area",
            area: "Square",
            areaEffect: "Damage",
            base: '2d6',
            damageType: "poison",
            savingThrow: "constitution",
            saveEffect: "No Damage",       
            sound: "",
            macro: '!Spell;Putrid Radiance;2',
            tempImg: "https://files.d20.io/images/469625735/mK7gnOSOteATSiJs5Z7riA/thumb.png?1767216572",
            tempSize: 10,
            fx: 'explode-slime',
            when: "start",
            savingThrow: "auto",
            saveText: "The Putrid clears",
            note: "Target is Poisoned for a round",
        },



        "Ray of Enfeeblement": {
            name: "Ray of Enfeeblement",
            level: 2,
            spellType: "DirectAttack",
            range: 60,
            concentration: true,
            autoHit: "No",
            when: "start",
            failText: " will be Feeble while spell lasts",
            when: "endAll",
            savingThrow: "constitution",
            spellType: "Misc",
            sound: "Laser",
            fx: "",
            macro: '!Spell;Ray of Enfeeblement;0;%Selected%;%Target%',
        },



        "Ray of Frost": {
            name: "Ray of Frost",
            level: 0,
            spellType: "DirectAttack",
            range: 60,
            autoHit: "No",
            when: "start",
            savingThrow: "auto",
            saveText: "Movement is slowed by 10ft this turn",
            base: '1d8',
            cLevel: {5: '2d8', 11: '3d8'},
            damageType: "cold",
            note: "Target's Speed is reduced by 10 for a turn",
            sound: "Laser",
            emote: "A frigid beam of blue-white light streaks toward the target",
            fx: "",
            macro: '!Spell;Ray of Frost;0;%Selected%;%Target%',
        },

        "Ray of Sickness": {
            name: "Ray of Sickness",
            level: 1,
            spellType: "DirectAttack",
            range: 60,
            autoHit: "No",
            base: '2d8',
            sLevel: [0,"2d8","3d8","4d8","5d8","6d8","7d8"],
            damageType: "poison",
            sound: "Laser",
            emote: "A ray of sickening greenish energy lashes out toward the target. <br>[#ff0000]If hit, the target must also make a Constitution Saving throw or be Poisoned for a round[/#]",
            fx: "beam-slime",
            macro: '!Spell;Ray of Sickness;%Level%;%Selected%;%Target%',
        },



        "Sacred Flame": {
            name: "Sacred Flame",
            level: 0,
            spellType: "DirectAttack",
            range: 60,
            autoHit: "No",
            savingThrow: "dexterity",
            saveEffect: "No Damage",
            base: '1d8',
            cLevel: {5: '2d8', 11: '3d8'},
            damageType: "radiant",
            sound: "Angels",
            emote: "Flame-like radiance descends on the Target",
            fx: "glow-fire",
            macro: '!Spell;Sacred Flame;0;%Selected%;%Target%',
        },



        "Sanctuary": {
            name: "Sanctuary",
            level: 1,
            bonusAction: true,
            range: 30,
            beneficial: true,
            spellType: "Misc",
            duration: 10,
            emote: "As a bonus action, You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn’t protect the warded creature from area effects, such as the explosion of a fireball. If the warded creature makes an attack or casts a spell that affects an enemy creature, this spell ends.",
            macro: "!Spell;Sanctuary;1;%Selected%;%Target%",
            sound: "Angels",
        },

        "Searing Smite": {
            name: "Searing Smite",
            level: 1,
            bonusAction: true,
            range: 5,
            beneficial: true,
            duration: 10,
            concentration: true,
            spellType: "Misc",
            emote: "The next hit deals extra Fire Damage and may cause the target to Ignite in flames",
            macro: "!Spell;Searing Smite;1",
            sound: "Angels",
        },

        "Shield of Faith": {
            name: "Shield of Faith",
            level: 1,
            bonusAction: true,
            range: 60,
            beneficial: true,
            duration: 100,
            concentration: true,
            spellType: "Misc",
            emote: "A shimmering field appears and surrounds your target within range, granting it a +2 bonus to AC.",
            macro: "!Spell;Shield of Faith;1;%Selected%;%Target%",
            sound: "Angels",
        },

        "Shillelagh": {
            name: "Shillelagh",
            level: 0,
            bonusAction: true,
            duration: 10,
            concentration: false,
            spellType: "Misc",
            sound: "Woosh",
            macro: '!Spell;Shillelagh;0;%Selected%;%Selected%',
            fx: '',
            emote: "%%Caster%% imbues his weapon with the Power of Nature!",            
        },



        "Sleep": {
            name: "Sleep",
            emote: "Using a pinch of fine sand, %%Caster%% sends creatures into a magical slumber. They remain asleep unless they take damage or are delliberately awakened",
            level: 1,
            range: 90,
            duration: 10,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            failText: " falls asleep",
            sound: "FFire",
            macro: '!Spell;Sleep;%Level%',
            tempImg: 'https://files.d20.io/images/464585187/odP4Dv5gqpOgxA4GtmGIMA/thumb.webp?1763427066',
            tempSize: 40,
            fx: "explode-magic",
        },

        "Sleet Storm": {
            level: 2,
            name: "Sleet Storm",
            range: 150,
            spellType: "Ongoing",
            duration: 10,
            concentration: true,
            area: 'special',
            effect: "Effect",
            moveEffect: "map",
            tempImg: 'https://files.d20.io/images/470245401/Ng752wa8aromwPeXjumBCA/thumb.png?1767632656',
            tempSize: 80,
            sound: "Thunder",
            macro: '!Spell;Sleet Storm;3',
            emote: "The ground in the area is covered with slick ice, making it difficult terrain. When a creature enters the spell’s area for the first time on a turn or starts its turn there, it must make a Dexterity saving throw. On a failed save, it falls prone. If a creature is concentrating in the spell’s area, the creature must make a successful Constitution saving throw against your spell save DC or lose concentration.", 
            charID: '-OiE7OCHSibssu2PskVE',
        },


        "Spike Growth": {
            level: 2,
            name: "Spike Growth",
            range: 150,
            spellType: "Ongoing",
            duration: 100,
            concentration: true,
            base: '2d4',
            damageType: "piercing",
            area: 'special',
            effect: "Damage",
            moveEffect: "map",
            tempImg: 'https://files.d20.io/images/467719558/sFDuFb5emZeavny7OaHurg/thumb.png?1765684299',
            tempSize: 40,
            sound: "Entangle",
            macro: '!Spell;Spike Growth;2',
            emote: "The ground erupts in hard spikes and thorns. The area become difficult terrain and causes damage for any creature moving within.",
            charID: '-OgPtm6w70voqIqyYk1X',
        },

        "Spirit Guardians": {
            level: 3,
            name: "Spirit Guardians",
            range: 0,
            spellType: "Ongoing",
            duration: 100,
            concentration: true,
            base: '3d8',
            sLevel: [0,0,0,"3d8","4d8","5d8","6d8","7d8"],
            damageType: "radiant",
            savingThrow: "wisdom",
            moveEffect: "map",
            moveWithCaster: true,
            saveEffect: "Half Damage",
            area: 'special',
            effect: "Damage",
            tempImg: 'https://files.d20.io/images/469636544/3188t5F5Z-oDCN7qS9VUhg/thumb.png?1767228260',
            tempSize: 30,
            sound: "Angels",
            fx: "glow-holy",
            macro: '!Spell;Spirit Guardians;%Level%',
            emote: "Angelic Spirits surround the Caster. Enemies in the area will take damage and have their speed halved.",
            charID: '',
        },

        "Spiritual Weapon": {
            level: 2,
            name: "Spiritual Weapon",
            range: 60,
            spellType: "Ongoing",
            duration: 10,
            concentration: false,
            base: '1d8',
            sLevel: [0,"1d8","2d8","3d8","4d8","5d8","6d8","7d8"],
            damageType: "force",
            area: 'special',
            effect: "Damage",
            tempImg: 'https://files.d20.io/images/469703229/QMOjuEu7LjRvI49jnuwftg/thumb.png?1767301303',
            tempSize: 5,
            sound: "Angels",
            macro: '!Spell;Spiritual Weapon;%Level%;%Selected%',
            emote: "A Weapon of pure Force appears and can be moved to attack any target within range (60 feet)",
            charID: '-OhvKvkbLTJaap8L0gQl',
        },




        "Thunderous Smite": {
            name: "Thunderous Smite",
            level: 1,
            bonusAction: true,
            range: 5,
            beneficial: true,
            duration: 10,
            concentration: true,
            spellType: "Misc",
            emote: "The next hit deals extra thunder Damage and may knock the target prone and away",
            macro: "!Spell;Thunderous Smite;1;",
            sound: "Angels",
        },



        "Thunderwave": {
            name: "Thunderwave",
            level: 1,
            range: 5,
            spellType: "Area",
            area: "Square",
            areaEffect: "Damage",
            base: '3d6',
            damageType: "thunder",
            sLevel: [0,'2d6',"3d6","4d6","5d6","6d6","7d6"],    
            savingThrow: "constitution",
            saveEffect: "Half Damage",       
            sound: "Thunder",
            macro: '!Spell;Thunderwave;%Level%',
            tempImg: "https://files.d20.io/images/464597646/OEF2m9OvLSy6J_WrL4Mh7Q/thumb.png?1763433964",
            tempSize: 15,
            fx: 'breath-smoke',
        },

        "Web": {
            name: "Web",
            level: 2,
            range: 60,
            duration: 600,
            concentration: true,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            savingThrow: "dexterity",
            when: "action",
            actionSave: "strength",
            conditionImmune: "restrained",
            saveText: " and remains free to act",
            failText: " and is restrained by the webs",
            moveEffect: "map",
            sound: "Web",
            macro: '!Spell;Web;2',
            emote: "A creature restrained by the webs can use its action to make a Strength check against your spell save DC. If it succeeds, it is no longer restrained. The webs are flammable. Any 5-foot cube of webs exposed to fire burns away in 1 round, dealing 2d4 fire damage to any creature that starts its turn in the fire. The Area remains Difficult Ground and Light Cover",
            tempImg: 'https://files.d20.io/images/466161281/XBL47z2Lc4rAKNcT7M4jjA/thumb.png?1764547188',
            tempSize: 20,
            fx: "",
        },

        "Wrathful Smite": {
            name: "Wrathful Smite",
            level: 1,
            bonusAction: true,
            range: 5,
            beneficial: true,
            duration: 10,
            concentration: true,
            spellType: "Misc",
            emote: "The next hit deals extra Psychic Damage and may cause the target to Flee",
            macro: "!Spell;Wrathful Smite;1;",
            sound: "Angels",
        },

    }

