

    const SpellInfo = {

        "Ray of Frost": {
            level: 0,
            spellType: "DirectAttack",
            range: 60,
            autoHit: "No",
            base: '1d8',
            cLevel: {5: '2d8', 11: '3d8'},
            damageType: "cold",
            note: "Target's Speed is reduced by 10 for a turn",
            applyMarker: true,
            sound: "Laser",
            emote: "A frigid beam of blue-white light streaks toward the target",
            fx: "",
            macro: '!Spell;Ray of Frost;0;%Selected%;%Target%',
        },
        "Acid Splash": {
            level: 0,
            range: 60,
            spellType: "DirectAttack",
            autoHit: "No",
            base: '1d6',
            cLevel: {5: '2d6', 11: '3d6'},
            damageType: "acid",
            savingThrow: "dexterity",
            saveEffect: "No Damage",
            emote: '%%Caster%% hurls a bubble of acid at the target',
            sound: "Plasma",
            macro: '!Spell;Acid Splash;0;%Selected%;%Target%',
        },
        "Burning Hands": {
            level: 1,
            range: 15,
            spellType: "Area",
            base: '3d6',
            sLevel: [0,'3d6',"4d6","5d6","6d6","7d6","8d6"],
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            area: 'Cone',
            areaEffect: "Damage",
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            sound: "Flames",
            macro: '!Spell;Burning Hands;%Level%',
            fx: "breath-fire",
        },
        "Magic Missile": {
            level: 1,
            range: 120,
            spellType: "DirectAttack",
            autoHit: "Yes",
            base: '3d4+3',
            sLevel: [0,'3d4+4','4d4+4','5d4+5','6d4+6','7d4+7'],
            damageType: "force",
            macro: '!Spell;Magic Missile;%Level%;%Selected%;%Target%',
            emote: "%%Caster%% creates glowing darts of magical force which strike the target",
            sound: "Splinter2",
            fx: "missile-magic",
        },
        "Sleep": {
            emote: "Using a pinch of fine sand, %%Caster%% sends creatures into a magical slumber. They remain asleep unless they take damage or are delliberately awakened",
            level: 1,
            range: 90,
            duration: 10,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            savingThrow: "No",
            areaTextF: " falls asleep",
            effectMarker: "status_KO::2006544",
            sound: "FFire",
            macro: '!Spell;Sleep;%Level%',
            tempImg: 'https://files.d20.io/images/464585187/odP4Dv5gqpOgxA4GtmGIMA/thumb.webp?1763427066',
            tempSize: 40,
            fx: "explode-magic",
        },
        "Entangle": {
            level: 1,
            range: 90,
            duration: 10,
            concentration: true,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            savingThrow: "strength",
            when: "action",
            conditionImmune: "restrained",
            areaTextS: " and remains free to act",
            areaTextF: " and is restrained by the vines",
            effectMarker: "status_Restrained-or-Webbed::2006494",
            moveEffect: "map",
            sound: "Entangle",
            macro: '!Spell;Entangle;1',
            emote: "The Area remains Difficult Ground. Restrained Creatures must use their Action, making a Strength Save to Break out.",
            tempImg: 'https://files.d20.io/images/464592489/MlFXxUdwYnkx-S5mHam-KQ/thumb.png?1763430837',
            tempSize: 20,
            fx: "explode-slime",
        },
        "Faerie Fire": {
            level: 1,
            range: 60,
            duration: 10,
            concentration: true,
            spellType: "Area",
            area: "Square",
            areaEffect: "Effect",
            savingThrow: "dexterity",
            areaTextS: "",
            areaTextF: " and is outlined by Faerie Fire",
            effectAura: "#ff00ff",
            sound: "FFire",
            macro: '!Spell;Faerie Fire;1',
            tempImg: "https://files.d20.io/images/464592488/Ol6oEZ2kLqqfV-fEBHrq5Q/thumb.png",
            tempSize: 20,
            fx: 'explode-magic',
        },
        "Thunderwave": {
            level: 1,
            range: 5,
            spellType: "Area",
            area: "Square",
            areaEffect: "Damage",
            base: '3d6',
            damageType: "thunder",
            sLevel: [0,'2d6',"3d6","4d6","5d6","6d6","7d6"],    
            savingThrow: "constitution",
            saveEffect: "Half Damage",       
            sound: "Thunder",
            macro: '!Spell;Thunderwave;%Level%',
            tempImg: "https://files.d20.io/images/464597646/OEF2m9OvLSy6J_WrL4Mh7Q/thumb.png?1763433964",
            tempSize: 15,
            fx: 'breath-smoke',
        },
        "Fog Cloud": {
            level: 1,
            spellType: "Area",
            area: "Square",
            sound: "Woosh",
            range: 120,
            duration: 600,
            concentration: true,
            emote: 'The Fog can be blown away by a strong wind. ',
            areaEffect: "Graphic",
            moveEffect: "map",
            macro: '!Spell;Fog Cloud;%Level%',
            tempImg: "https://files.d20.io/images/464601122/Z_72GfzK6nldIvjjv9Kusw/thumb.png?1763436289",
            tempSize: 'Level * 40',
        },
        "Produce Flame": {
            level: 0,
            range: 30,
            autoHit: "No",
            spellType: "DirectAttack",
            base: '1d8',
            cLevel: {5: '2d8', 11: '3d8'},
            damageType: "fire",
            sound: "Plasma",
            macro: '!Spell;Produce Flame;0;%Selected%;%Target%',
            emote: "%%Caster%% hurls a ball of flame at the target",
            fx: "",
        },
        "Cure Wounds": {
            level: 1,
            range: 5,
            spellType: "Misc",
            sound: "Angels",
            macro: "!Spell;Cure Wounds;%Level%;%Selected%",
        },
        "Divine Favour": {
            level: 1,
            duration: 10,
            concentration: true,
            range: "Self",
            spellType: "Misc",
            macro: "!Spell;Divine Favour;1;%Selected%",
            emote: "Your prayer empowers you with divine radiance. Until the spell ends, your weapon attacks deal an extra 1d4 radiant damage on a hit.<br>Casting this only takes a Bonus Action",
            sound: "Angels",
            marker: true,
        },
        "Shield of Faith": {
            level: 1,
            range: 60,
            duration: 100,
            concentration: true,
            spellType: "Misc",
            emote: "A shimmering field appears and surrounds your target within range, granting it a +2 bonus to AC.",
            macro: "!Spell;Shield of Faith;1;%Selected%;%Target%",
            sound: "Angels",
        },
        "Protection from Evil and Good": {
            level:1,
            duration: 100,
            concentration: true,
            range: 5,
            spellType: "Misc",
            emote: "The creature you touch is granted Protection against certain creatures.",
            macro: "!Spell;Protection from Evil and Good;1;%Selected%;%Target%",
            sound: "Angels",
            marker: true,
        },
        "Sanctuary": {
            level: 1,
            range: 30,
            spellType: "Misc",
            duration: 10,
            emote: "As a bonus action, You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn’t protect the warded creature from area effects, such as the explosion of a fireball. If the warded creature makes an attack or casts a spell that affects an enemy creature, this spell ends.",
            macro: "!Spell;Sanctuary;1;%Selected%;%Target%",
            sound: "Angels",
            marker: true,
        },
        "Mage Armour": {
            level: 1,
            range: 5,
            spellType: "Misc",
            emote: "You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends.The target’s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.",
            macro: "!Spell;Mage Armour;1;%Selected%;%Target%",
            sound: "Angels",
            marker: true,
        },
        "Web": {
            level: 2,
            range: 60,
            duration: 600,
            concentration: true,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            savingThrow: "dexterity",
            when: "action",
            conditionImmune: "restrained",
            areaTextS: " and remains free to act",
            areaTextF: " and is restrained by the webs",
            effectMarker: "status_Restrained-or-Webbed::2006494",
            moveEffect: "map",
            sound: "Web",
            macro: '!Spell;Web;2',
            emote: "A creature restrained by the webs can use its action to make a Strength check against your spell save DC. If it succeeds, it is no longer restrained. The webs are flammable. Any 5-foot cube of webs exposed to fire burns away in 1 round, dealing 2d4 fire damage to any creature that starts its turn in the fire. The Area remains Difficult Ground and Light Cover",
            tempImg: 'https://files.d20.io/images/466161281/XBL47z2Lc4rAKNcT7M4jjA/thumb.png?1764547188',
            tempSize: 20,
            fx: "",
        },
        "Dragon's Breath": {
            level: 2,
            range: 5,
            duration: 10,
            concentration: true,
            spellType: "Misc",
            sound: "Ding",
            damageType: "fire",
            emote: "Your target gains the ability to breath magical in a 15 foot cone, doing 3d6 damage, 1/2 on a successful Dex Saving Throw.",
            macro: "!Spell;Dragon's Breath;%Level%;%Selected%;%Target%;?{Energy Type|Acid|Cold|Fire|Lightning|Poison}",
            targetBecomesCaster: true,
            alternates: ["damageType"],
        },
        "Breathe": {
            name: "Breathe",
            level: 2,
            range: 15,
            spellType: "Area",
            base: '3d6',
            sLevel: [0,0,"3d6","4d6","5d6","6d6","7d6"],
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            area: 'Cone',
            areaEffect: "Damage",
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            sound: "Flames",
            fx: "breath-fire",
        },
        "Hold Person": {
            level: 2,
            range: 60,
            duration: 10,
            concentration: true,
            when: "end",
            spellType: "Misc",
            macro: "!Spell;Hold Person;%Level%;%Selected%;%Target%",
            sound: "Sound",
            marker: true,
            marker: "Restrained",
            targetSave: "wisdom",
            emote: "The Target can make a Wisom Save at the end of each of its turns.",
        },
        "Moonbeam": {
            level: 2,
            name: "Moonbeam",
            range: 120,
            spellType: "Ongoing",
            duration: 10,
            concentration: true,
            base: '2d10',
            sLevel: [0,0,"2d10","3d10","4d10","5d10","6d10"],
            damageType: "radiant",
            savingThrow: "constitution",
            saveEffect: "Half Damage",
            area: 'Square',
            areaEffect: "Damage",
            tempImg: 'https://files.d20.io/images/466342179/VLWwiNSk5g-QKmRkYZ77qA/thumb.png?1764706936',
            tempSize: 10,
            sound: "Beam",
            fx: "glow-holy",
            macro: '!Spell;Moonbeam;%Level%',
            moveEffect: "objects",
            emote: "A silvery beam of pale light shines down in a 5-foot- radius, 40-foot-high cylinder centered on a point within range. Creatures starting their turn in the Moonbeam take damage. The Caster can move the Beam on each of their turns up to 60 feet.",
            charID: '-OfVsgHiqLOZjV357ox_',
        },


    }

