

    const SpellInfo = {

        "Acid Splash": {
            name: "Acid Splash",
            level: 0,
            range: 60,
            spellType: "DirectAttack",
            autoHit: "No",
            base: '1d6',
            cLevel: {5: '2d6', 11: '3d6'},
            damageType: "acid",
            savingThrow: "dexterity",
            saveEffect: "No Damage",
            emote: '%%Caster%% hurls a bubble of acid at the target',
            sound: "Plasma",
            macro: '!Spell;Acid Splash;0;%Selected%;%Target%',
        },

        "Barkskin": {
            name: "Barkskin",
            level: 2,
            range: 5,
            beneficial: true,
            spellType: "Misc",
            emote: "You touch a willing creature. Until the spell ends, the target’s skin has a rough, bark-like appearance, and the target’s AC can’t be less than 16, regardless of what kind of armor it is wearing.",
            macro: "!Spell;Barkskin;2;%Selected%;%Target%",
            sound: "Entangle",
            concentration: true,
            duration: 600,
        },

        "Bless": {
            name: "Bless",
            level: 1,
            range: 30,
            beneficial: true,
            spellType: "Misc",
            emote: "You Bless up to 3 creatures of your choice within range.",
            macro: "!Spell;Bless;1;%Selected%;%Target1%;%Target2%;%Target3%",
            sound: "Angels",
            concentration: true,
            duration: 10,
        },

        "Breathe": {
            name: "Breathe",
            level: 2,
            range: 15,
            spellType: "Area",
            duration: 10,
            base: '3d6',
            sLevel: [0,0,"3d6","4d6","5d6","6d6","7d6"],
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            area: 'Cone',
            areaEffect: "Damage",
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            sound: "Flames",
            fx: "breath-fire",
        },

        "Burning Hands": {
            name: "Burning Hands",
            level: 1,
            range: 15,
            spellType: "Area",
            base: '3d6',
            sLevel: [0,'3d6',"4d6","5d6","6d6","7d6","8d6"],
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            area: 'Cone',
            areaEffect: "Damage",
            tempImg: 'https://files.d20.io/images/105823565/P035DS5yk74ij8TxLPU8BQ/thumb.png?1582679991',
            tempSize: 5,
            sound: "Flames",
            macro: '!Spell;Burning Hands;%Level%',
            fx: "breath-fire",
        },

         "Cure Wounds": {
            name: "Cure Wounds",
            beneficial: true,
            level: 1,
            range: 5,
            heal: "1d8 + level + Bonus",
            spellType: "Misc",
            sound: "Angels",
            macro: "!Spell;Cure Wounds;%Level%;%Selected%",
        },

        "Divine Favour": {
            name: "Divine Favour",
            level: 1,
            duration: 10,
            beneficial: true,
            concentration: true,
            range: "Self",
            spellType: "Misc",
            macro: "!Spell;Divine Favour;1;%Selected%",
            emote: "Your prayer empowers you with divine radiance. Until the spell ends, your weapon attacks deal an extra 1d4 radiant damage on a hit.<br>Casting this only takes a Bonus Action",
            sound: "Angels",
        },       

        "Dragon's Breath": {
            name: "Dragon's Breath",
            level: 2,
            range: 5,
            duration: 10,
            concentration: true,
            friendlySpell: true,
            spellType: "Misc",
            sound: "Ding",
            damageType: "fire",
            emote: "%%Target%% gains the ability to breath magical in a 15 foot cone.",
            macro: "!Spell;Dragon's Breath;%Level%;%Selected%;%Target%;?{Energy Type|Acid|Cold|Fire|Lightning|Poison}",
            alternates: ["damageType"],
        },

        "Entangle": {
            name: "Entangle",
            level: 1,
            range: 90,
            duration: 10,
            concentration: true,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            savingThrow: "strength",
            when: "action",
            conditionImmune: "restrained",
            saveText: " and remains free to act",
            failText: " and is restrained by the vines",
            moveEffect: "map",
            sound: "Entangle",
            macro: '!Spell;Entangle;1',
            emote: "The Area remains Difficult Ground. Restrained Creatures must use their Action, making a Strength Save to Break out.",
            tempImg: 'https://files.d20.io/images/464592489/MlFXxUdwYnkx-S5mHam-KQ/thumb.png?1763430837',
            tempSize: 20,
            fx: "explode-slime",
        },

        "Faerie Fire": {
            name: "Faerie Fire",
            level: 1,
            range: 60,
            duration: 10,
            concentration: true,
            spellType: "Area",
            area: "Square",
            areaEffect: "Effect",
            savingThrow: "dexterity",
            failText: " and is outlined by Faerie Fire",
            sound: "FFire",
            macro: '!Spell;Faerie Fire;1',
            tempImg: "https://files.d20.io/images/464592488/Ol6oEZ2kLqqfV-fEBHrq5Q/thumb.png",
            tempSize: 20,
            fx: 'explode-magic',
        },

        "Flame Blade": {
            name: "Flame Blade",
            level: 2,
            duration: 100,
            concentration: true,
            spellType: "Misc",
            sound: "Woosh",
            macro: '!Spell;Flame Blade;%Level%',
            fx: 'burn-fire',
            emote: "%%Caster%% evokes a Fiery Blade as a Bonus Action",            
        },

        "Flaming Sphere": {
            level: 2,
            name: "Flaming Sphere",
            range: 60,
            spellType: "Ongoing",
            duration: 10,
            concentration: true,
            base: '2d6',
            sLevel: [0,0,"2d6","3d6","4d6","5d6","6d6"],
            damageType: "fire",
            savingThrow: "dexterity",
            saveEffect: "Half Damage",
            area: 'special',
            effect: "Damage",
            tempImg: 'https://files.d20.io/images/467704024/63vhnKhZNoVRWYEwBz8uTQ/thumb.png?1765676435',
            tempSize: 15,
            sound: "Inferno",
            fx: "glow-fire",
            macro: '!Spell;Flaming Sphere;%Level%',
            emote: "A sphere of fire appears within range. Any creature entering the sphere takes damage. The sphere can be moved 30 feet and into other creatures, who take damage, stopping the sphere",
            charID: '-OgPVj8fUQkF1eJDvbWI',
        },

        "Fog Cloud": {
            name: "Fog Cloud",
            level: 1,
            spellType: "Area",
            area: "Square",
            sound: "Woosh",
            range: 120,
            duration: 600,
            concentration: true,
            emote: 'The Dense Fog blocks vision into/out of or through it.<br>The Fog can be blown away by a strong wind.',
            areaEffect: "Graphic",
            moveEffect: "map",
            macro: '!Spell;Fog Cloud;%Level%',
            tempImg: "https://files.d20.io/images/464601122/Z_72GfzK6nldIvjjv9Kusw/thumb.png?1763436289",
            tempSize: 'Level * 40',
        },

         "Healing Word": {
            name: "Healing Word",
            level: 1,
            beneficial: true,
            range: 60,
            heal: "1d4 + level + Bonus",
            spellType: "Misc",
            sound: "Angels",
            emote: "As a Bonus Action",
            macro: "!Spell;Healing Word;%Level%;%Selected%;%Target%",
        },

        "Heat Metal": {
            name: "Heat Metal",
            level: 2,
            range: 60,
            duration: 10,
            concentration: true,
            when: "start",
            macro: "!Spell;Heat Metal;%Level%;%Selected%;%Target%",
            sound: "Woosh",
            savingThrow: "constitution",
            emote: "",
            when: "start",
            spellType: "DirectAttack",
            saveText: " and may drop/remove the Object<br>",
            failText: " and must drop/remove the Object<br>",
            autoHit: "Yes",
            base: '2d8',
            sLevel: [0,0,"2d8","3d8","4d8","5d8","6d8"],
            damageType: "fire",
            saveEffect: "Special",
        },


        "Heroism": {
            name: "Heroism",
            beneficial: true,
            level: 1,
            range: 5,
            spellType: "Misc",
            emote: "%%Target%% is imbued with bravery, immune to being frightened and gains temporary hp each round.",
            macro: "!Spell;Heroism;1;%Selected%;%Target%",
            sound: "Angels",
            concentration: true,
            duration: 10,
        },


        "Hold Person": {
            name: "Hold Person",
            level: 2,
            range: 60,
            duration: 10,
            concentration: true,
            when: "endAll",
            spellType: "Misc",
            macro: "!Spell;Hold Person;%Level%;%Selected%;%Target%",
            sound: "Sound",
            savingThrow: "wisdom",
            saveText: " and is not Held.",
            failText: " and is Held",
            emote: "The Target can make a Wisdom Save at the end of each of its turns.",
        },

        "Mage Armour": {
            name: "Mage Armour",
            level: 1,
            range: 5,
            spellType: "Misc",
            emote: "You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends.The target’s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.",
            macro: "!Spell;Mage Armour;1;%Selected%;%Target%",
            sound: "Angels",
        },

        "Magic Missile": {
            name: "Magic Missile",
            level: 1,
            range: 120,
            spellType: "DirectAttack",
            autoHit: "Yes",
            base: '3d4+3',
            sLevel: [0,'3d4+4','4d4+4','5d4+5','6d4+6','7d4+7'],
            damageType: "force",
            macro: '!Spell;Magic Missile;%Level%;%Selected%;%Target%',
            emote: "%%Caster%% creates glowing darts of magical force which strike the target",
            sound: "Splinter2",
            fx: "missile-magic",
        },

        "Magic Weapon": {
            name: "Magic Weapon",
            level: 2,
            beneficial: true,
            range: 5,
            spellType: "Misc",
            emote: "%%Caster%% enchants a weapon to be magical!",
            macro: "!Spell;Magic Weapon;%Level%;%Selected%;%Target%",
            sound: "FFire",
            concentration: true,
            duration: 600,

        },

        "Moonbeam": {
            level: 2,
            name: "Moonbeam",
            range: 120,
            spellType: "Ongoing",
            duration: 10,
            concentration: true,
            base: '2d10',
            sLevel: [0,0,"2d10","3d10","4d10","5d10","6d10"],
            damageType: "radiant",
            savingThrow: "constitution",
            saveEffect: "Half Damage",
            area: 'special',
            effect: "Damage",
            tempImg: 'https://files.d20.io/images/466342179/VLWwiNSk5g-QKmRkYZ77qA/thumb.png?1764706936',
            tempSize: 10,
            sound: "Beam",
            fx: "glow-holy",
            macro: '!Spell;Moonbeam;%Level%',
            emote: "A silvery beam of pale light shines down in a 5-foot- radius, 40-foot-high cylinder centered on a point within range. Creatures entering or starting their turn in the Moonbeam take damage. The Caster can move the Beam on each of their turns up to 60 feet.",
            charID: '-OfVsgHiqLOZjV357ox_',
        },

        "Produce Flame": {
            name: "Produce Flame",
            level: 0,
            range: 30,
            autoHit: "No",
            spellType: "DirectAttack",
            base: '1d8',
            cLevel: {5: '2d8', 11: '3d8'},
            damageType: "fire",
            sound: "Plasma",
            macro: '!Spell;Produce Flame;0;%Selected%;%Target%',
            emote: "%%Caster%% hurls a ball of flame at the target",
            fx: "",
        },

        "Protection from Evil and Good": {
            level:1,
            name: "Protection from Evil and Good",
            duration: 100,
            beneficial: true,
            concentration: true,
            range: 5,
            spellType: "Misc",
            emote: "The creature you touch is granted Protection against certain creatures.",
            macro: "!Spell;Protection from Evil and Good;1;%Selected%;%Target%",
            sound: "Angels",
        },

        "Ray of Frost": {
            name: "Ray of Frost",
            level: 0,
            spellType: "DirectAttack",
            range: 60,
            autoHit: "No",
            when: "start",
            savingThrow: "auto",
            saveText: "Movement is slowed by 10ft this turn",
            base: '1d8',
            cLevel: {5: '2d8', 11: '3d8'},
            damageType: "cold",
            note: "Target's Speed is reduced by 10 for a turn",
            sound: "Laser",
            emote: "A frigid beam of blue-white light streaks toward the target",
            fx: "",
            macro: '!Spell;Ray of Frost;0;%Selected%;%Target%',
        },

        "Sanctuary": {
            name: "Sanctuary",
            level: 1,
            range: 30,
            beneficial: true,
            spellType: "Misc",
            duration: 10,
            emote: "As a bonus action, You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn’t protect the warded creature from area effects, such as the explosion of a fireball. If the warded creature makes an attack or casts a spell that affects an enemy creature, this spell ends.",
            macro: "!Spell;Sanctuary;1;%Selected%;%Target%",
            sound: "Angels",
        },

        "Searing Smite": {
            name: "Searing Smite",
            level: 1,
            range: 5,
            beneficial: true,
            duration: 10,
            concentration: true,
            spellType: "Misc",
            emote: "The next hit deals extra Fire Damage and may cause the target to Ignite in flames",
            macro: "!Spell;Searing Smite;%Level%;",
            sound: "Angels",
        },

        "Shield of Faith": {
            name: "Shield of Faith",
            level: 1,
            range: 60,
            beneficial: true,
            duration: 100,
            concentration: true,
            spellType: "Misc",
            emote: "A shimmering field appears and surrounds your target within range, granting it a +2 bonus to AC.",
            macro: "!Spell;Shield of Faith;1;%Selected%;%Target%",
            sound: "Angels",
        },

        "Sleep": {
            name: "Sleep",
            emote: "Using a pinch of fine sand, %%Caster%% sends creatures into a magical slumber. They remain asleep unless they take damage or are delliberately awakened",
            level: 1,
            range: 90,
            duration: 10,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            failText: " falls asleep",
            sound: "FFire",
            macro: '!Spell;Sleep;%Level%',
            tempImg: 'https://files.d20.io/images/464585187/odP4Dv5gqpOgxA4GtmGIMA/thumb.webp?1763427066',
            tempSize: 40,
            fx: "explode-magic",
        },

        "Spike Growth": {
            level: 2,
            name: "Spike Growth",
            range: 150,
            spellType: "Ongoing",
            duration: 100,
            concentration: true,
            base: '2d4',
            damageType: "piercing",
            area: 'special',
            effect: "Damage",
            moveEffect: "map",
            tempImg: 'https://files.d20.io/images/467719558/sFDuFb5emZeavny7OaHurg/thumb.png?1765684299',
            tempSize: 40,
            sound: "Entangle",
            macro: '!Spell;Spike Growth;2',
            emote: "The ground erupts in hard spikes and thorns. The area become difficult terrain and causes damage for any creature moving within.",
            charID: '-OgPtm6w70voqIqyYk1X',
        },

        "Thunderous Smite": {
            name: "Thunderous Smite",
            level: 1,
            range: 5,
            beneficial: true,
            duration: 10,
            concentration: true,
            spellType: "Misc",
            emote: "The next hit deals extra thunder Damage and may knock the target prone and away",
            macro: "!Spell;Thunderous Smite;1;",
            sound: "Angels",
        },



        "Thunderwave": {
            name: "Thunderwave",
            level: 1,
            range: 5,
            spellType: "Area",
            area: "Square",
            areaEffect: "Damage",
            base: '3d6',
            damageType: "thunder",
            sLevel: [0,'2d6',"3d6","4d6","5d6","6d6","7d6"],    
            savingThrow: "constitution",
            saveEffect: "Half Damage",       
            sound: "Thunder",
            macro: '!Spell;Thunderwave;%Level%',
            tempImg: "https://files.d20.io/images/464597646/OEF2m9OvLSy6J_WrL4Mh7Q/thumb.png?1763433964",
            tempSize: 15,
            fx: 'breath-smoke',
        },

        "Web": {
            name: "Web",
            level: 2,
            range: 60,
            duration: 600,
            concentration: true,
            spellType: "Area",
            area: 'Square',
            areaEffect: "Effect",
            savingThrow: "dexterity",
            when: "action",
            actionSave: "strength",
            conditionImmune: "restrained",
            saveText: " and remains free to act",
            failText: " and is restrained by the webs",
            moveEffect: "map",
            sound: "Web",
            macro: '!Spell;Web;2',
            emote: "A creature restrained by the webs can use its action to make a Strength check against your spell save DC. If it succeeds, it is no longer restrained. The webs are flammable. Any 5-foot cube of webs exposed to fire burns away in 1 round, dealing 2d4 fire damage to any creature that starts its turn in the fire. The Area remains Difficult Ground and Light Cover",
            tempImg: 'https://files.d20.io/images/466161281/XBL47z2Lc4rAKNcT7M4jjA/thumb.png?1764547188',
            tempSize: 20,
            fx: "",
        },

        "Wrathful Smite": {
            name: "Wrathful Smite",
            level: 1,
            range: 5,
            beneficial: true,
            duration: 10,
            concentration: true,
            spellType: "Misc",
            emote: "The next hit deals extra Psychic Damage and may cause the target to Flee",
            macro: "!Spell;Wrathful Smite;1;",
            sound: "Angels",
        },

    }

