

    const WeaponInfo = {
        Longsword: {
            cat: "Weapon",
            base: '1d8',
            properties: "Versatile",
            damageType: "slashing",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Sword",
        },
        Dagger: {
            cat: "Weapon",
            base: '1d4',
            properties: "Finesse, Thrown",
            damageType: "slashing",
            type: "Melee,Ranged",
            range: [20,60],
            critOn: 20,
            sound: "Club",
        },
        Acornbringer: {
            cat: "Weapon",
            base: '1d1',
            properties: "Finesse",
            damageType: "piercing",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Sword",
        },
        'Quarterstaff (2H)': {
            cat: "Weapon",
            base: '1d8',
            properties: "",
            damageType: "bludgeoning",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Staff",
        },
        'Scimitar': {
            cat: "Weapon",
            base: "1d6",
            properties: "Finesse",
            damageType: "slashing",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Sword",
        },
        'Dire Wolf Bite': {
            cat: "Weapon",
            base: "2d6",
            properties: "",
            damageType: "piercing",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Beast",
            special: "If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.",
        },
        "Bear Bite": {
            cat: "Weapon",
            base: "1d8",
            properties: "",
            damageType: "piercing",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Beast",
            special: "",
        },
        "Bear Claws": {
            cat: "Weapon",
            base: "2d6",
            properties: "",
            damageType: "slashing",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Beast",
            special: "If the target is a Large or smaller creature, it has the Prone condition",
        },
        "Hand Crossbow": {
            cat: "Weapon",
            base: "1d6",
            properties: "",
            damageType: "piercing",
            type: "Ranged",
            range: [30,120],
            critOn: 20,
            sound: "Arrow",
            special: "",
        },
        "Light Crossbow": {
            cat: "Weapon",
            base: "1d8",
            properties: "",
            damageType: "piercing",
            type: "Ranged",
            range: [80,320],
            critOn: 20,
            sound: "Arrow",
            special: "",
        },
        'Spear (2H)': {
            cat: "Weapon",
            base: "1d8",
            properties: "",
            damageType: "piercing",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Sword",
        },
        'Mace': {
            cat: "Weapon",
            base: "1d6",
            properties: "",
            damageType: "bludgeoning",
            type: "Melee",
            range: [0,0],
            critOn: 20,
            sound: "Staff",
        },



    }
